/***************************************************************************
 *                                                                         *
 * Auto Generated BY CodeComment                                           *
 * Copyright(C) 2000-2016, JiangSu Yinhe Electronic Co.Ltd.                *
 * All Rights Reserved.                                                    *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Yinhe Elec Co.Ltd.       *
 * The copyright notice above does not evidence any actual or intended     *
 * publication of such source code.                                        *
 *                                                                         *
 **************************************************************************/



(function($){
    $.fn.FontScroll = function(options,timerArray){
        var d = {time: 3000,s: 'fontColor',num: 1}
        var o = $.extend(d,options);
        

        $(".gd").addClass('line');
        var _con = $('.line').eq(0);
        var _conH = _con.height(); //�����ܸ߶�
        var _conChildH = _con.find('tr').eq(0).height();//һ�ι����߶�
        var _temp = _conChildH;  //��ʱ����
        var _time = d.time;  //�������
        var _s = d.s;  //�������


       // _con.clone().insertAfter(_con);//��ʼ����¡

        //��ʽ����
        var num = d.num;
        var _p = this.find('tr');
        var allNum = _p.length;

        _p.eq(num).addClass(_s);


        timerArray[0] = setInterval(Up,_time);
		this.hover(function(){clearInterval(timerArray[0])},function(){timerArray[0] = setInterval(Up,_time);});

        function Up(){
            _con.animate({marginTop: '-'+_conChildH});
            //��ʽ����
            _p.removeClass(_s);
            num += 1;
            _p.eq(num).addClass(_s);
            
            if(_conH == _conChildH){
                _con.animate({marginTop: '-'+_conChildH},"normal",over);
            } else {
                _conChildH += _temp;
            }
        }
        function over(){
            _con.attr("style",'margin-top:0');
            _conChildH = _temp;
            num = 1;
            _p.removeClass(_s);
            _p.eq(num).addClass(_s);
        }
    }
})(jQuery);
