/***************************************************************************
 *                                                                         *
 * Auto Generated BY CodeComment                                           *
 * Copyright(C) 2000-2016, JiangSu Yinhe Electronic Co.Ltd.                *
 * All Rights Reserved.                                                    *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Yinhe Elec Co.Ltd.       *
 * The copyright notice above does not evidence any actual or intended     *
 * publication of such source code.                                        *
 *                                                                         *
 **************************************************************************/

/**
 * Internationalization of jquery.msgbox
 * Add this file to HTML head before jquery.msgbox
 */
 
(function ($) {

	$.msgboxI18N = {};
	
	// Simplified Chinese
	$.msgboxI18N.zh_CN = {
		OK: '好',
		Cancel: '取消',
		Loading: '正在加载',
		Next: '下一张',
		'Play/Pause': '播放/暂停',
		Prev: '上一张',
		Maximize: '最大化',
		Minimize: '最小化',
		Close: '关闭',
		imgError: '图片加载失败！',
		xhrError: 'Ajax请求失败！'
	};
	
	// Tranditional Chinese
	$.msgboxI18N.zh_TW = {
		OK: '好',
		Cancel: '取消',
		Loading: '正在加載',
		Next: '下一張',
		'Play/Pause': '播放/暫停',
		Prev: '上一張',
		Maximize: '最大化',
		Minimize: '最小化',
		Close: '關閉',
		imgError: '圖片加載失敗！',
		xhrError: 'Ajax請求失敗！'
	};
	

})(jQuery);