/***************************************************************************
 *                                                                         *
 * Auto Generated BY CodeComment                                           *
 * Copyright(C) 2000-2016, JiangSu Yinhe Electronic Co.Ltd.                *
 * All Rights Reserved.                                                    *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Yinhe Elec Co.Ltd.       *
 * The copyright notice above does not evidence any actual or intended     *
 * publication of such source code.                                        *
 *                                                                         *
 **************************************************************************/

/**
 * @ ynj
 * @since 20151120 不再使用， 转移到模板中去
 * @since 20160118 从模板中转出继续使用
 * 
 */

var urland = '&';


if (typeof($) ==  'undefined') {
	//document.write('<script src="../assets/plugins/jquery/jquery-1.9.1.min.js"></script>');
}

function chargeSidebar(id_li,id_a){ //change the sidebar's class;
   	$("#"+id_li).click();
    $("#"+id_li).addClass("active");
    $("#"+id_a).addClass("active");
}

$(function() {
	setInterval("GetTime()", 1000);
	$("#select_all").click(selectAllClick); // 无AJAX刷新页面预设事件，AJAX刷新页面需要使用不能使用select_all,同时页面中书写onclick事件

	// message 变成弹窗
	if (typeof(showMessage) !=  'undefined') {
		showMessage();
	}
	if (typeof(sessionRemove) !=  'undefined') {
		sessionRemove();
	}
});


function sessionRemove() {
	var sessionRemoveInPage = "";
	var sessionRemoveInSetting = "";
	var sessionRemoveMuniteInSetting = 180000;
	try {
		
		//页面预设，如bms页面无论用户是否设置退出都将不主动退出
		sessionRemoveInPage = $("#sessionRemove").attr("value"); 
		// 用户设置，对于不需要主动刷新的页面则采用根据用户设置进行是否退出以及多久退出
		sessionRemoveInSetting = $("#sessionRemoveInSetting").attr("value"); 
		// 用户设置，对于设置需要退出的则获取其退出的时间。
		sessionRemoveMuniteInSetting = $("#sessionRemoveMuniteInSetting").attr("value") * 1000 * 60;
	} catch (e) {
		console.log(e);
	}
	if (sessionRemoveInPage != "" && (sessionRemoveInPage == false || sessionRemoveInPage == "false")) {
		console.log("sessionRemoveInPage dose not turn on!");
	} else {
		if (sessionRemoveInSetting != "" 
			&& (sessionRemoveInSetting == true || sessionRemoveInSetting == "true")) {
			if (!sessionRemoveMuniteInSetting) {
				sessionRemoveMuniteInSetting = 180000;
			}
			console.log("sessionRemove turn on! microsecond:" + sessionRemoveMuniteInSetting);
			setInterval("logout()", sessionRemoveMuniteInSetting);
		} else {
			console.log("sessionRemoveInSetting dose not turn on!");
		}
	}
}

function logout() {
	$(".id_logout").click();
}

function showMessageNotUsedSine2016(){
	var o = $("#p_operator_message");
	if (o == undefined) {
		return ;
	}
	var message = o.html();
	if (message == undefined) {
		return ;
	}
	
	if (message.indexOf("成功") != -1 || message.indexOf("SUCCESS") != -1) {
		// sweetAlert("操作成功", $("#p_operator_message").html(), "success");
		// $.jMessageBox.show("系统信息",$("#p_operator_message").html()+"\n");
		$.msgbox({
			type : 'success',
			content : $("#p_operator_message").html(),
			icons: ['min', 'max', 'close'],
    		id: 0,
			title : '操作成功'
		});
	} else if (message != "") {
		// sweetAlert("操作出错", $("#p_operator_message").html(), "error");
		// $.jMessageBox.show("系统信息",$("#p_operator_message").html()+"\n");
		$.msgbox({
			type : 'error',
			content : $("#p_operator_message").html(),
			icons: ['min', 'max', 'close'],
    		id: 0,
			title : '操作出错'
		});
	}
}


function GetTime() {
	var mydate = new Date();
	var str = "" + mydate.getFullYear() + "/";
	str += (mydate.getMonth() + 1) + "/";
	str += mydate.getDate();
	var hour = mydate.getHours();
	var min = mydate.getMinutes();
	var sec = mydate.getSeconds();
	if (10 > hour) {
		hour = "0" + hour;
	}
	if (10 > min) {
		min = "0" + min;
	}
	if (10 > sec) {
		sec = "0" + sec;
	}
	$("#timer").html(str + " " + hour + ":" + min + ":" + sec);
}


function selectAllClick() {
	var status = $(this).prop("checked")
	$("input[type='checkbox'][name='select_item']").each(function() {
		$(this).prop("checked",status);
	});
}

function selectAllAjaxClick(id) {
	var status = document.getElementById(id).checked;
	$("input[type='checkbox']").each(function() {
		$(this).prop("checked",status);
	});
}

function chargeSidebar(id_li,id_a){ //change the sidebar's class;
    $("#"+id_li).click();
    $("#"+id_li).addClass("active");
    $("#"+id_a).addClass("active");
}