package com.yinhe.server.AcsServer.enums;

import com.yinhe.server.AcsServer.util.Resources;

public enum CPEResultCode {
	//Add
	CPE_ADD_SERIALNUMBER_IS_NULL,
	CPE_ADD_MACADDRESS_IS_NULL,
	CPE_ADD_MACADDRESS_TPYE_ERROR,
	CPE_ADD_MACADDRESS_EXIST,
	CPE_ADD_POSITION_NULL,
	CPE_ADD_POSITION_NAME_NULL,
	CPE_ADD_SERIALNUMBER_EXIST,
	CPE_ADD_SUCCESS,
	CPE_ADD_UNKNOWN_ERROR,
	CPE_ADD_DEVICE_EXIST,
	
	//Delete
	CPE_DELETE_CHECKED_IS_NULL,
	CPE_DELETE_CHECKED_ERROR,
	CPE_DELETE_CHECKED_SUCCESS,
	CPE_DELETE_TASK_RUNNING,
	CPE_DELETE_UNKNOWN_ERROR,
	
	//update
	CPE_UPDATE_CHECKED_IS_NULL,
	CPE_UPDATE_CHECKED_SUCCESS,
	CPE_UPDATE_UNKNOWN_ERROR,
	
	//设备名和IP
	CPE_UPDATE_VALUE_NULL,
	CPE_UPDATE_SUCCESS,
	CPE_UPDATE_FAILED,
		
	CPE_IS_NULL;
	
	
	
	
	
	
	public String toLocalString() {
		return Resources.getLocalName(this.name());
	}
}
