/***************************************************************************
 *                                                                         *
 * Auto Generated BY CodeComment                                           *
 * Copyright(C) 2000-2016, JiangSu Yinhe Electronic Co.Ltd.                *
 * All Rights Reserved.                                                    *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Yinhe Elec Co.Ltd.       *
 * The copyright notice above does not evidence any actual or intended     *
 * publication of such source code.                                        *
 *                                                                         *
 **************************************************************************/

package com.yinhe.server.AcsServer.enums;

import com.yinhe.server.AcsServer.util.Resources;


public enum PersonalInfoErrorCode {
	NOT_LOGIN,
	USER_NOT_EXIST,
	PASSWORD_INPUT_NULL,
	PASSWORD_NOT_MATCH,
	EMAIL_HAS_EXIST,
	PHONENUMBER_HAS_EXIST,
	USERNAME_HAS_EXIST,
	UPDATE_PERSONAL_INFO_SUCCESS,
	UPDATE_PERSONAL_INFO_FAILED,
	MODIFY_PERSONAL_INFO_SUCCESS,
	MODIFY_PERSONAL_INFO_FAILED,
	UPDATE_PERSONAL_INFO_AND_PASSWORD_SUCCESS,
	UPDATE_PERSONAL_INFO_AND_PASSWORD_FAILED;
	
	public String toLocalString() {
		return Resources.getLocalName("PersonalInfoErrorCode." + this.name());
	}
}
