package com.yinhe.server.AcsServer.enums;

import com.yinhe.server.AcsServer.util.Resources;

public enum SystemOperateResultCode {
	ADD_NODE_TASK_NULL,
	ADD_NODE_TASK_ERROR,
	ADD_NODE_TASK_SUCCESS,
	ADD_NODE_TASK_EXIST,
	
	DELETE_NODE_FOR_TASK_FAILED,
	DELETE_NODE_FOR_TASK_SUCCESS,
	DELETE_NODE_FOR_TASK_NULL,
	
	DELETE_PARAM_GET_SUCCESS,
	DELETE_PARAM_GET_FAILED,
	DELETE_PARAM_GET_NULL,	
	ADD_PARAM_GET_SUCCESS,
	ADD_SOME_PARAM_GET_EXIST,
	ADD_PARAM_GET_FAILED,
	ADD_PARAM_GET_NULL,
	
	UPDATE_PARAM_ONE,
	UPDATE_PARAM_NULL,
	UPDATE_PARAM_SUCCESS,
	UPDATE_PARAM_FAILED,
	PARAM_MAXORMIN_NULL,
	PARAM_VALUE_TYPE_NULL,
	PARAM_OTHER_VALUE_NULL,
	PARAM_MAX_MIN_ERROR,
	
	DELETE_TASK_SUCCESS,
	DELETE_TASK_NULL,
	DELETE_TASK_FAILED,
	DELETE_TASK_RUNNING,
	ADD_TASK_SUCCESS,
	ADD_TASK_NULL,
	ADD_TASK_FAILED,
	ADD_TASK_EXIST,
	
	DELETE_PARAM_SET_SUCCESS,
	DELETE_PARAM_SET_FAILED,
	DELETE_PARAM_SET_NULL,	
	ADD_PARAM_SET_SUCCESS,
	ADD_SOME_PARAM_SET_EXIST,
	ADD_PARAM_SET_FAILED,
	ADD_PARAM_SET_NULL;
	
	public String toLocalString() {
		return Resources.getLocalName(this.name());
	}
}
