package com.yinhe.server.AcsServer.enums;

import com.yinhe.server.AcsServer.util.Resources;

public enum TaskResultCode {
	//connect
	TASK_REQUEST_CPE_CONNECTION_OK,
	TASK_REQUEST_CPE_CONNECTION_ERROR,
	TASK_REQUEST_CPE_TIMEOUT,
	TASK_REQUEST_CPE_URL_NULL,
	
	TASK_RESULT_PARAMETER_NULL,
	TASK_RESULT_DEVICE_BUSY,	
	
	TASK_START_OK,
	TASK_START_ERROR,
	TASK_START_TIMEOUT,
	TASK_START_SUCCESS_GETPARAM_TIMEOUT,
	TASK_START_Connected_SetParamUnknown,
	TASK_START_PARAMETERS_NOT_YET_APPLIED,
	TASK_START_HOST_ERROR,
	TASK_START_PORT_ERROR,
	TASK_START_PORT_OR_HOST_NULL,
//	TASK_START_NEED_FILL_IN_FULL,
	TASK_START_NUMBER_TYPE_ERROR,
	TASK_START_PORT_OR_HOST_ERROR,
	TASK_START_TIME_IS_NULL,
	TASK_START_DSCP_IS_NULL,
	TASK_START_TIMES_REPEAT_IS_NULL,
	TASK_START_DATA_BLOCK_SIZE_IS_NULL,
	TASK_START_HOST_IS_NULL,
	TASK_START_PORT_IS_NULL,
	TASK_START_CHANNEL_IS_NULL,
	TASK_START_VIDEO_MAX_SIZE_IS_NULL,
	TASK_START_START_TIME_IS_NULL,
	TASK_START_END_TIME_IS_NULL,
	TASK_START_TIME_LESS_END_TIME,
	TASK_RESULT_FREQUENCY_IS_NULL,
	TASK_RESULT_LEVEL_IS_NULL,
	TASK_RESULT_SYMBOLRATE_IS_NULL,
	TASK_RESULT_MODULATION_IS_NULL,
	
	//stop
	TASK_STOP_OK,
	TASK_STOP_ERROR,
	TASK_STOP_TIMEOUT,
	
	//reboot
	TASK_REBOOT_ERROR,
	TASK_REBOOT_OK,
	TASK_REBOOT_TIMEOUT,
	
	//update
	TASK_UPDATE_ERROR,
	TASK_UPDATE_OK,
    TASK_UPDATE_TIMEOUT,
    TASK_UPDATE_UNKNOWN,
    
    //record
    TASK_START_RECORD_OK,
    TASK_START_RECORD_ERROR,
    TASK_START_RECORD_TIMEOUT,
	
	TASK_RESULTCODE_9000,
	TASK_RESULTCODE_9001,
	TASK_RESULTCODE_9002,
	TASK_RESULTCODE_9003,
	TASK_RESULTCODE_9004,
	TASK_RESULTCODE_9005,
	TASK_RESULTCODE_9006,
	TASK_RESULTCODE_9007,
	TASK_RESULTCODE_9008,
	TASK_RESULTCODE_9009,
	TASK_RESULTCODE_9010,
	TASK_RESULTCODE_9011,
	TASK_RESULTCODE_9012,
	TASK_RESULTCODE_9013,
	TASK_RESULTCODE_9014,
	TASK_RESULTCODE_9015,
	TASK_RESULTCODE_9016,
	TASK_RESULTCODE_9017,
	TASK_RESULTCODE_9018,
	TASK_RESULTCODE_9019;	
		
	public String toLocalString() {
		return Resources.getLocalName(this.name());
	}
}
